# Generated by Django 5.2.18 on 2026-10-06 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.PositiveIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)])),
                ('servicio', models.CharField(max_length=100)),
                ('especialista', models.CharField(choices=[('Gasfitería general', 'Gasfitería general'), ('Detección de fugas', 'Detección de fugas'), ('Instalación sanitaria', 'Instalación sanitaria'), ('Mantención de calefón', 'Mantención de calefón'), ('Destapes', 'Destapes')], max_length=60)),
                ('reputacion', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('correo_contacto', models.EmailField(max_length=100)),
                ('direccion', models.CharField(choices=[('Av. Providencia 1200, Providencia', 'Av. Providencia 1200, Providencia'), ('Av. Irarrázaval 2400, Ñuñoa', 'Av. Irarrázaval 2400, Ñuñoa'), ('San Diego 850, Santiago', 'San Diego 850, Santiago'), ('Av. Vicuña Mackenna 7200, La Florida', 'Av. Vicuña Mackenna 7200, La Florida')], max_length=160)),
                ('hora_atencion', models.TimeField()),
                ('telefono_contacto', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{8,15}$', 'Ingresa entre 8 y 15 dígitos, con + opcional al inicio.')])),
            ],
            options={
                'verbose_name': 'servicio',
                'verbose_name_plural': 'servicios',
                'ordering': ['id_servicio'],
            },
        ),
    ]
