# Generated by Django 5.2.18 on 2026-10-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasfiteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='telefono_contacto',
            field=models.CharField(max_length=16),
        ),
    ]
